### PR TITLE
Logo

### LINKED ISSUE #20: todo: logo
My design skills are seriously lacking, would take contributions.

### PR DESCRIPTION
**Pull request by G07cha**
My friend have done logo for bloxparty but for some reason he doesn't want to expose himself. If you have
any suggestions or thoughts about current logo, feel free to comment in this PR and I'll give it to author.

**Things to do before merge:**
- [x] Windows logo
- [x] OSX logo
- [x] Linux logo

Logo

screen shot 2015-11-03 at 3 59 58 pm

screen shot 2015-11-03 at 4 30 28 pm

Fixes #20

### CODE REVIEW

**Comment by kvnneff** [comment]
Awesome!  The layout looks good to me, but maybe we could get it in a darker color?

I've been using Ultimate Tetris as inspiration for the design: https://www.google.com/search?q=ultimate+tetris&espv=2&biw=1141&bih=637&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMIt_vWwcv0yAIVTtpjCh11NAwb#tbm=isch&q=tetris+ultimate

If your friend wants to pick a color out of there to fit the darker theme then I can go back and incorporate the logo colors into the design of the game the next time I iterate over it.  The red I don't think I can work into the layout.

**Comment by G07cha** [comment]
What do you think about this one? 

Blue logo

**Comment by kvnneff** [comment]
Looks great!

**Comment by G07cha** [comment]
Wow, you are fast, I'm haven't even committed new logo yet. Okay then, I'll commit to `master` branch.

**Comment by kvnneff** [comment]
Oops!  I wasn't paying attention :)

**Pull request merged**
